spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Jikimi_open?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update  #create update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

org:
  springframework:
    security:
      web: trace

logging.level:
  org.hibernate.SQL: debug #??? sql? ??? ??? ????.
  org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6
  org.springframework.security.web: trace
  org.springframework.web: debug
  org.springframework.http.converter: trace
